name: 'Publish docs to GitHub Pages'
description: 'Action that publishes docs to the ghpages branch'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
  username:
    description: 'Username for doc generation commits'
    default: 'docs-bot'
  email:
    description: 'Email for doc generation commits'
    default: 'docs-bot@github.com'
  timeout:
    description: 'Timeout for waiting until docs are generated, in seconds (default: 60)'
    default: 120,
  baseUrl:
    description: 'The GitHub Pages base URL for your repo'
  pagesBranch:
    description: 'The branch set up to serve Github Pages (default: gh-pages)'
    default: 'gh-pages'

runs:
  using: 'composite'
  steps:
    - name: Find .git directory
      run: ls -la
      shell: bash
    - name: Build docs
      run: |
        yarn
        yarn next build
        yarn next export
        ls -la $GITHUB_ACTION_PATH/out
      working-directory: ${{ github.action_path }}
      shell: bash
    # - run: node dist/index.js
    #   working-directory: ${{ github.action_path }}
    #   shell: bash
    - name: Push built docs to GitHub Pages branch
      run: |
        git config --global user.email "${{ inputs.email }}"
        git config --global user.name "${{ inputs.username }}"
        git fetch
        echo ${{ inputs.pagesBranch }}
        git switch -c ${{ inputs.pagesBranch }}
        git clean -f -d
        git reset --hard origin/${{ inputs.pagesBranch }}
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo $GITHUB_SHA
        echo "short sha"
        echo $SHORT_SHA
        cp -r $GITHUB_ACTION_PATH/out ./$SHORT_SHA
        git add .
        git commit -m "Publishing docs for $SHORT_SHA"
        git push origin ${{ inputs.pagesBranch }}
      shell: bash
    - run: node dist/checkPagesDeploy.js
      working-directory: ${{ github.action_path }}
      shell: bash
