name: 'Publish docs to GitHub Pages'
description: 'Action that publishes docs to the ghpages branch'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
  username:
    description: 'Username for doc generation commits'
  email:
    description: 'Email for doc generation commits'
  timeout:
    description: 'Timeout for waiting until docs are generated, in seconds (default: 60)'
  pagesBranch:
    description: 'The branch set up to serve Github Pages (default: gh-pages)'

runs:
  using: 'composite'
  steps:
    - name: Find .git directory
      run: ls -la
      shell: bash
    - run: yarn && yarn next build && yarn next export
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: node dist/index.js
      working-directory: ${{ github.action_path }}
      shell: bash
    - name: Push built docs to GitHub Pages branch
    run: |
      git fetch
      git switch -c ${{ inputs.pagesBranch }}
      git clean -f -d
      git add .
      git commit -m "Publishing docs"
      git push origin ${{ inputs.pagesBranch }}
    # shell: bash
    # - run: node dist/poll.js
    #   working-directory: ${{ github.action_path }}
    #   shell: bash
